### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by chanklish** [yoonwaiyan/stackskills-dl#11]
Hello my friend
I am trying to run your stackskills-dl on windows.
I installed ruby on windows and downloaded the stackskills-dl zip file.
what shall i do next ?
I have 0 knowledge in programming 
Please help

**Comment by yoonwaiyan** [comment]
Hi there, I'm sorry but this project is not GUI-friendly for non-developers and I don't think it's running well on Windows as it seems to yield some network error. If you're interested, you can learn a little bit of commands and try install Ruby(programming language) and related plugins as mentioned in README. 

I'll add some notes for Windows users later on, let me close this issue for now.
