### ISSUE TITLE
Any ideas?

### ISSUE THREAD

**Issue by aceoverclocked** [yoonwaiyan/stackskills-dl#13]
So i'm an absolute newbie when it comes to this stuff. I bought some courses from Stackskills and i was warned they're scam and the courses will be gone in a few days so i'm trying to download them.
I went as far as this. Any way it can be fixed, i'd really appreciate it c:
![untitled](https://cloud.githubusercontent.com/assets/26586629/24179206/f7873b64-0ead-11e7-806a-f855364e7430.png)

**Comment by aceoverclocked** [comment]
Found this but no idea how to apply it:
https://github.com/yoonwaiyan/stackskills-dl/commit/5f303798698b45d23cdbe956f9881f24ebceabec
also another issue arises when downloading a course that does have the download button
![untitled](https://cloud.githubusercontent.com/assets/26586629/24180781/3fc6f80c-0eb7-11e7-9756-9a0f927a4e34.png)

**Comment by yoonwaiyan** [comment]
For the first issue, can you try revert the code as changed in https://github.com/yoonwaiyan/stackskills-dl/commit/1596f8539a8cbe62d761d75f5897053e164453d5 ? For the second issue, can you try out the suggestion as mentioned in https://github.com/yoonwaiyan/stackskills-dl/issues/5 ?

**Comment by yoonwaiyan** [comment]
Since there's no response, I'll close this issue for now, stated README that Windows is not supported for now.

**Comment by yoonwaiyan** [comment]
Update: This issue resonates with issue #26 .
