### ISSUE TITLE
Unable to download some courses

### ISSUE THREAD

**Issue by PoiSonS** [yoonwaiyan/stackskills-dl#14]
Hi,

first of all, i would like to thank you for all the efforts you have put to build/write this script that we all thankfully use.

back to the issue; I tried to download two different courses both are failing with use of both option:
**-c** and **-cs**

the error return are as following:

- using **-c** 
- input: `ruby stackskills_dl.rb -cs https://stackskills.com/courses/enrolled/77462`

- error:
`Login Email: ############### `
`Login password: *******`
`Login Successfully.`
`Finding https://stackskills.com/courses/enrolled/77462 from your list of courses`
`Unable to find this course: https://stackskills.com/courses/enrolled/77462 from your list of courses.`

- using **-cs**
- input: `ruby stackskills_dl.rb -cs https://stackskills.com/courses/red-hat-linux-centos-rhcsa/lectures/788977`

- error:
`Login Email: ################`
`Login password: *******`
`Login Successfully.`
`/var/lib/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:656:in 'resolve': absolute URL needed (not s) (ArgumentError)`
	`from /var/lib/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:234:in 'fetch'`
	`from /var/lib/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize.rb:464:in 'get'`
	`from /home/trng/Downloads/stackskills-dl-master/lib/course_finder.rb:84:in 'get_course_link_from_slug'`
	`from /home/trng/Downloads/stackskills-dl-master/lib/course_finder.rb:96:in 'get_course_links'`
	`from /home/trng/Downloads/stackskills-dl-master/lib/course_finder.rb:27:in 'execute'`
	`from /home/trng/Downloads/stackskills-dl-master/lib/course_finder.rb:10:in 'run'`
	`from stackskills_dl.rb:8:in '<main>'`

I did install all the required gem `sudo bundle install --gemfile=Gemfile` (Gemfile that included on the same folder of the script.

*my apology for making this to long but I want to make it easy for troubleshooting.*

thanks and best regards,

**Comment by yoonwaiyan** [comment]
Hi there, for **-cs** option please try the course link `https://stackskills.com/courses/red-hat-linux-centos-rhcsa` instead of the lecture link as this meant to download the entire course but not a lecture.

**Comment by PoiSonS** [comment]
Hi @yoonwaiyan ,

really appreciate your prompt response, 

i have tried -cs with the course URL "https://stackskills.com/courses/red-hat-linux-centos-rhcsa " instead of lecture URL, but unfortunately the below error has been occur:

`Login Successfully.`
`/var/lib/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:656:in 'resolve': absolute URL needed (not s) (ArgumentError)`
`	from /var/lib/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:234:in 'fetch'`
	`from /var/lib/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize.rb:464:in 'get'`
	`from /home/trng/Downloads/stackskills-dl-master/lib/course_finder.rb:84:in 'get_course_link_from_slug'`
	`from /home/trng/Downloads/stackskills-dl-master/lib/course_finder.rb:96:in 'get_course_links'`
	`from /home/trng/Downloads/stackskills-dl-master/lib/course_finder.rb:27:in 'execute'`
	`from /home/trng/Downloads/stackskills-dl-master/lib/course_finder.rb:10:in 'run'`
	`from stackskills_dl.rb:8:in '<main>'`

thanks for help and support.

**Comment by yoonwaiyan** [comment]
Issue was caused by command argument which couldn't parse more than one character. Solved by changing the command to `-s` instead of `-cs`.
