### ISSUE TITLE
--help arguments need to be rectify

### ISSUE THREAD

**Issue by PoiSonS** [yoonwaiyan/stackskills-dl#15]
Dear @yoonwaiyan ,

the "help" arguments need to be rectify as `-c` and `-cs` is missing.

as shown below:

> **ruby stackskills_dl.rb --help**
> Usage: ruby stackskills_dl.rb [options]
>     -u, --email NAME                            #        Email
>     -p, --password PASSWORD             #                       Password
>         --course COURSE_URL                 #                   Course URL in ID.
>     -c, --course-slug COURSE_SLUG        #                            Course URL in slug.

thanks and best regards,

**Comment by yoonwaiyan** [comment]
Thanks for reporting, it's related to #14. Solved now.
