### ISSUE TITLE
Issue using the script

### ISSUE THREAD

**Issue by emehran** [yoonwaiyan/stackskills-dl#16]
Hello there. I'm trying to use your script on Mac but I get the following error

/Users/user/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- highline/import (LoadError)

Could you help please

**Comment by yoonwaiyan** [comment]
Please run `bundle install` before running the script.

**Comment by emehran** [comment]
Thanks worked
