### ISSUE TITLE
Script doesn't find courses on page 2 onwards.

### ISSUE THREAD

**Issue by saintograph** [yoonwaiyan/stackskills-dl#17]
I'm able to download courses on the first page : 
[https://stacksocial.usefedora.com/courses/enrolled](https://stacksocial.usefedora.com/courses/enrolled)

but not from page 2 onwards:
[https://stacksocial.usefedora.com/courses/enrolled?page=2](https://stacksocial.usefedora.com/courses/enrolled?page=2)

```
WARN: Unresolved specs during Gem::Specification.reset:
      unf_ext (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Login Successfully.
Finding https://stackskills.com/courses/enrolled/22936 from your list of courses
Unable to find this course: https://stackskills.com/courses/enrolled/22936 from your list of courses.
```

**Comment by yoonwaiyan** [comment]
May I know how many courses do you have? I couldn't get enough courses to show me the second page.

**Comment by saintograph** [comment]
I have 33 courses listed on my dashboard. Each page lists 12 courses.

**Comment by yoonwaiyan** [comment]
I've tried https://stacksocial.usefedora.com/courses/enrolled using my own account but it redirects me back to stackskills.com, and inside my page with 35 courses it's displayed as one page, I'm unable to access a second page of My Courses in Stackskills.

Pull request is welcomed if you've figured out the solution using your account, much thanks.

**Comment by saintograph** [comment]
Okie-dokie. I'm closing this.

**Comment by nbctcp** [comment]
I encouter same issue.
I need to key in email and password again.
How to fix that?
tq

STEPS TAKEN:
# apt install gem ruby-dev youtube-dl wget
# gem update --system
# gem install json bundler rake rainbow
# git clone https://github.com/yoonwaiyan/stackskills-dl.git
# cd stackskills-dl/
# bundle install

PROBLEMS:
# ruby stackskills_dl.rb -u "user@gmail.com" -p "password" -s "https://stackskills.com/courses/enrolled/137514"
WARN: Unresolved specs during Gem::Specification.reset:
      unf_ext (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Login Email:
