### ISSUE TITLE
Download in lower quality

### ISSUE THREAD

**Issue by rbariviera** [yoonwaiyan/stackskills-dl#19]
Is there any possible to download videos in another resolution ? ex: 640p

**Comment by yoonwaiyan** [comment]
For attached videos, seems like the resolution is being fixed so it'll download whatever resolution that's available in the "Download" buttton, while for wistia's videos, currently it's been working with a little bit of hack which I couldn't control the resolution with my limited knowledge. Do prompt me if you have any idea on how to control the resolution from url or inside the iframe.

**Comment by yoonwaiyan** [comment]
Closing this issue, please re-open if there's any new idea on this. Thanks.
