### ISSUE TITLE
undefined local variable or method `dashboard_page'

### ISSUE THREAD

**Issue by NickB23** [yoonwaiyan/stackskills-dl#2]
Getting the following error when trying to download one course:

stackskills_dl.rb:50:in `find_course': undefined local variable or method `dashboard_page' for main:Object (NameError)
	from stackskills_dl.rb:76:in `<main>'

**Comment by yoonwaiyan** [comment]
Just did a quick fix on this error, please try again and let me know whether it's working on your side. Thanks.

**Comment by yoonwaiyan** [comment]
Will close this for now, feel free to re-open this issue if this still persists.
