### ISSUE TITLE
Login works but course can't be found

### ISSUE THREAD

**Issue by WeaveHubHQ** [yoonwaiyan/stackskills-dl#20]
Hi,

I'm trying your script which seems like it be very cool, but I get this error when trying to download a course:  https://stackskills.com/courses/enrolled/33308

This happens for any course listed within My Courses. 

Any thoughts?

**Comment by yoonwaiyan** [comment]
Can you paste the error message from your screen?

**Comment by WeaveHubHQ** [comment]
[image: Inline image 1]


Jason S. Lazerus, M.S., GPEN, GCIH, GCFE, GCED, GSEC

**Comment by yoonwaiyan** [comment]
I still couldn't see any error message, the image is not displaying.

**Comment by WeaveHubHQ** [comment]
root@kali:~/stackskills-dl# ruby stackskills_dl.rb --course
https://stackskills.com/courses/enrolled/33308
Login Email: jlazerus@infosecured.org
Login password: ********
Login Successfully.
Finding https://stackskills.com/courses/enrolled/33308 from your list of
courses
*Unable to find this course: https://stackskills.com/courses/enrolled/33308
<https://stackskills.com/courses/enrolled/33308> from your list of courses*.



Jason S. Lazerus, M.S., GPEN, GCIH, GCFE, GCED, GSEC

**Comment by yoonwaiyan** [comment]
Just fixed the issue related to get the course listing properly and improved login check. Please update the repo on your local and try again.

**Comment by WeaveHubHQ** [comment]
Will do shortly. Thanks!

Jason Lazerus M.S., GPEN, GCIH, GCFE, GCED, GSEC
InfoSecured

On May 8, 2017, at 10:22 AM, Yoon Wai Yan <notifications@github.com> wrote:

Just fixed the issue related to get the course listing properly and
improved login check. Please update the repo on your local and try again.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/yoonwaiyan/stackskills-dl/issues/20#issuecomment-299880916>,
or mute the thread

**Comment by WeaveHubHQ** [comment]
Hi,

So it looks like that fixed the issue.  Is there a way to download multiple
videos and keep them within a single folder for that section? See example
below.

What I'd like to do is to download all the videos in the section called
'Build your hacking environment' and put that in a folder using that name
instead of each video having its own folder.


![image](https://cloud.githubusercontent.com/assets/16708611/25828531/a1394202-341e-11e7-84a2-4da71d6bb481.png)



Jason S. Lazerus, M.S., GPEN, GCIH, GCFE, GCED, GSEC

**Comment by yoonwaiyan** [comment]
It's possible and a good idea too since other downloaders are doing it such way, but it'll take some time as it will be a major change in the code. I'll open another issue as a feature request as the reported issue is solved.

**Comment by WeaveHubHQ** [comment]
Thanks!

Jason Lazerus M.S., GPEN, GCIH, GCFE, GCED, GSEC
InfoSecured

On May 9, 2017, at 9:55 AM, Yoon Wai Yan <notifications@github.com> wrote:

It's possible and a good idea too since other downloaders are doing it such
way, but it'll take some time as it will be a major change in the code.
I'll open another issue as a feature request as the reported issue is
solved.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/yoonwaiyan/stackskills-dl/issues/20#issuecomment-300172071>,
or mute the thread
