### ISSUE TITLE
Problems with running the script.

### ISSUE THREAD

**Issue by DevMahix** [yoonwaiyan/stackskills-dl#22]
I am really new at this and want to get this script running, so please bear with me :D.
I did the following:
-> Installed Bundler 
-> Installed Mechanize gem.
On git bash when i run ruby stackskills_dl.rb i get the following:

    C:\Ruby23-x64\bin\ruby.exe: No such file or directory -- stackskills_dl.rb (LoadError)

If i drag the file i get the following:

    C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- ./lib/input (LoadError)       
    from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'       
    from F:/Documents and Settings/User/My Documents/Downloads/stackskills-dl-master/stackskills_dl.rb:1:in `<main>'

What em i doing wrong ?

**Comment by yoonwaiyan** [comment]
Please run the script inside the clone directory.

**Comment by DevMahix** [comment]
CMD opens and closes afterwards when i do that.

**Comment by DevMahix** [comment]
Tried to navigate to the clone directory on git bash. When i type $ ruby stackskills_dl.rb i get the following:

```
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- highline/import (LoadError)
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from F:/Documents and Settings/User/My Documents/Downloads/stackskills-dlmaster/lib/input.rb:2:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from stackskills_dl.rb:1:in `<main>'
```

**Comment by yoonwaiyan** [comment]
Please run bundle install within the directory to install the dependency.

**Comment by DevMahix** [comment]
When i run bundle install within the directory i get the following:

```
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby x64-mingw32

    ruby

    mechanize was resolved to 2.7.4, which depends on
      nokogiri (~> 1.6) was resolved to 1.6.7.2, which depends on
        ruby (< 2.3) x64-mingw32
```

**Comment by yoonwaiyan** [comment]
You'll have to install and make sure ruby has been installed properly. This is a Ruby script so it's pretty obvious to have ruby installed in your machine before running the script. 

Closing this issue as this is a non-issue.

**Comment by DevMahix** [comment]
Wow, such arrogance. Why bother posting something if you are going to be a dick to the consumers. 
FYI : I have ruby installed and its working properly.

**Comment by yoonwaiyan** [comment]
Sorry for my mistake of not detailing the error message, anyway an open source community should be free of profanity.

Please ignore my previous message. It's because the ruby installed in your system is not compatible with the mechanize gem. Seems like the installed Ruby is from RubyInstaller. Can you install ruby 2.3 from git bash and try again?

**Comment by DevMahix** [comment]
Made in work on Linux. On Windows 7 it gets stuck after I enter my login credentials.

**Comment by yoonwaiyan** [comment]
Okay. Closing this issue now.
