### ISSUE TITLE
undefined local variable or method `folder_name' for main:Object (NameError)

### ISSUE THREAD

**Issue by xpresservers** [yoonwaiyan/stackskills-dl#3]
static:stackskills-dl-master xxx$ ruby stackskills_dl.rb -c https://stackskills.com/courses/internet-of-things-with-arduino-blueprints
Login Email: ********@gmail.com
Login password:  ********
Login Successfully
Finding https://stackskills.com/courses/internet-of-things-with-arduino-blueprints from your list of courses
stackskills_dl.rb:78:in `<main>': undefined local variable or method `folder_name' for main:Object (NameError)

**Comment by yoonwaiyan** [comment]
Thanks, updated script with the bug fix.
