### ISSUE TITLE
stackskills-dl not working for multi-page lists of courses.

### ISSUE THREAD

**Issue by Datadelvers** [yoonwaiyan/stackskills-dl#35]
Hello,

I am regular user of the stackskills-dl script, but recently I have run into a problem. When downloading courses I have purchased all works well if the course can be found on 'https://stackskills.com/courses/enrolled'. But I noticed that courses on the second page of courses 'https://stackskills.com/courses/enrolled?page=2' can't be downloaded.

Would it be possible to implement this feature? 

Regards,

Daniel

**Comment by yoonwaiyan** [comment]
Hi @Datadelvers , this scripts supports multiple pages of courses. It's possible that they have changed their UI and I'm not aware of it. Let me check and get back to you with a bug fix if that's the case. Thanks for reporting.

**Comment by Datadelvers** [comment]
Thanks for the quick reply. Looking forward to a fix/workaround :+1:

**Comment by yoonwaiyan** [comment]
Hi @Datadelvers , are you trying to download courses from page 2 by using the `-c` or `-s` option or without any option?

**Comment by yoonwaiyan** [comment]
Found out a bug that cause courses couldn't be found when it's listed beyond first page when the options mentioned above is used. @Datadelvers please let me know whether this fix helps.

**Comment by Datadelvers** [comment]
@yoonwaiyan , I use the '-c' option. Now, lets try the fix.

**Comment by Datadelvers** [comment]
@yoonwaiyan , the fix allows courses beyond the first page to be downloaded as well. Perfect :-)
