### ISSUE TITLE
Invalid Login Credentials

### ISSUE THREAD

**Issue by fussballball** [yoonwaiyan/stackskills-dl#37]
Hi,
I just wanted to use your script to prepare me for a longer off-line stay
However, when replacing the example e-mail and password with my login credentials, and then running docker-compose run stackskills_dl the outcome is "Invalid Login Credentials"
I traced it back to the login_user! function, but am not fluid in Ruby, so cannot adapt the script. My guess would be that current_page_forms.first is not the login form? However, I do not 
I checked the login credentials by copy pasting them from the docker script to stackskills - they are correct.
Any ideas on what may cause this?

I am using git-bash on Windows

**Comment by yoonwaiyan** [comment]
Can you confirm the email and password are both in your copied docker-compose.yml not the example? If it's correct, can you run this instead:

```
$ docker run -it --rm -v $PWD/downloads:/usr/app/downloads stackskills-dl ruby stackskills_dl.rb 
```

and then input your email and password see if the script runs?

**Comment by fussballball** [comment]
In git bash, as it is not a TTY it does not work. Removing the -it part and replacing it with an "-i" results in:
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Mount denied:
The source path "C:/Users/USER/Downloads/stackskills-dl-master/stackskills-dl-master/downloads;C"
doesn't exist and is not known to Docker.
It seems strange to me that there is a ";C" after downloads
I also checked Dockers settings and the drive "C" is shared with docker

Edit:
I moved to powershell, and got it to work. 
The only adaption I had to make was changing
$ docker run -it --rm -v $PWD/downloads:/usr/app/downloads stackskills-dl ruby stackskills_dl.rb 
to:
$ docker run -it --rm -v $PWD/downloads:/usr/app/downloads stackskills-dl-**master_stackskills_dl** ruby stackskills_dl.rb 

Thanks for your help!

**Comment by yoonwaiyan** [comment]
Seems like the first error happens because there isn't a /downloads folder being created, I probably should commit a blank /downloads folder to make this work. I'll need to add some documentation for this as well.

Closing this issue for now but I'll keep track of this issue for further documentation, thanks for your info and help!
