### ISSUE TITLE
Failing to download using Docker-Compose

### ISSUE THREAD

**Issue by semtex41** [yoonwaiyan/stackskills-dl#42]
Hello, 

Looks like I am finding the following error after taking the following steps:

1) downloaded the master branch .zip
2) copied, edited, and renamed the docker-compose.yml
3) edited docker-compose.yml to add email and passwd. 
4) `$ docker-compose build`

5) `$ docker-compose run stackskills_dl`

```
Creating network "stackskills-dl-master_default" with the default driver
Loaded login credentials from environment variables.
/usr/app/lib/course_finder.rb:52:in `login_user!': undefined method `click' for nil:NilClass (NoMethodError)
        from /usr/app/lib/course_finder.rb:29:in `execute'
        from /usr/app/lib/course_finder.rb:12:in `block in run'
        from /usr/app/lib/utilities.rb:13:in `block in mkchdir'
        from /usr/app/lib/utilities.rb:12:in `chdir'
        from /usr/app/lib/utilities.rb:12:in `mkchdir'
        from /usr/app/lib/course_finder.rb:11:in `run'
        from stackskills_dl.rb:11:in `<main>'
```

I suspect it has something to with line 32 in course_finder.rb, but I do not know. 
More likely, something changed on the site. 
It is also worth noting the same behavior was observed on the Docker branch. 

This is my first attempt using this project and it looks like you have a lot of good work put into it. 
I cant wait to try it.

**Comment by yoonwaiyan** [comment]
Seems like a login issue to me. Please try the latest update and let me know whether it's working now (to show message when login failed).

**Comment by semtex41** [comment]
Downloaded the latest zip, extracted and ran the following:
`$ docker-compose down --rmi all`
`$ docker-compose build`
`$ docker-compose run stackskills_dl`

`Loaded login credentials from environment variables.
/usr/app/lib/course_finder.rb:52:in `login_user!': undefined local variable or method `user_dashboard' for #<CourseFinder:0x000055dc0b2fe2d8> (NameError)
        from /usr/app/lib/course_finder.rb:29:in `execute'
        from /usr/app/lib/course_finder.rb:12:in `block in run'
        from /usr/app/lib/utilities.rb:13:in `block in mkchdir'
        from /usr/app/lib/utilities.rb:12:in `chdir'
        from /usr/app/lib/utilities.rb:12:in `mkchdir'
        from /usr/app/lib/course_finder.rb:11:in `run'
        from stackskills_dl.rb:11:in `<main>'`

I also tried adding single quotes around the username and password values, with no success. 
Happy to help with the next steps, just let me know.

**Comment by yoonwaiyan** [comment]
Hey there, sorry for the late reply. I've made a working fix which now detects invalid login properly (verify your login credentials beforehand to avoid multiple docker rebuilds). Please try again after updating your local copy and let me know whether it works for you.

**Comment by yoonwaiyan** [comment]
Hey there, I'll be closing this issue for now for inactivity. If there's any new findings regarding the login issue, feel free to re-open the issue.
