### ISSUE TITLE
File Name too Long

### ISSUE THREAD

**Issue by itsbkm** [yoonwaiyan/stackskills-dl#46]
/usr/lib/ruby/2.3.0/fileutils.rb:253:in `mkdir': File name too long @ dir_s_mkdir - 04. Class_#4-_VC_Part_2-_Security-Legal_Structures_to_Protect_You_+_Make_You_More_$_-Due_diligence_and_how_to_assess_a_management_team._Security_structures._Legal_information_to_help_protect_you_and_your_investments-company._Venture_capital_history_is_very_important_to_understand.Due_diligence_and_how_to_assess_a_management_team._Security_structures._Legal_information_to_help_protect_you_and_your_investments-company._Venture_capital_history_is_very_important_to_understand-. (Errno::ENAMETOOLONG)
	from /usr/lib/ruby/2.3.0/fileutils.rb:253:in `fu_mkdir'
	from /usr/lib/ruby/2.3.0/fileutils.rb:227:in `block (2 levels) in mkdir_p'
	from /usr/lib/ruby/2.3.0/fileutils.rb:225:in `reverse_each'
	from /usr/lib/ruby/2.3.0/fileutils.rb:225:in `block in mkdir_p'
	from /usr/lib/ruby/2.3.0/fileutils.rb:211:in `each'
	from /usr/lib/ruby/2.3.0/fileutils.rb:211:in `mkdir_p'
	from /stackskills-dl-master/lib/utilities.rb:11:in `mkchdir'
	from /stackskills-dl-master/lib/lecture.rb:40:in `download'
	from /stackskills-dl-master/lib/course.rb:24:in `block (2 levels) in download'
	from /stackskills-dl-master/lib/course.rb:23:in `each'
	from /stackskills-dl-master/lib/course.rb:23:in `block in download'
	from /stackskills-dl-master/lib/utilities.rb:13:in `block in mkchdir'
	from /stackskills-dl-master/lib/utilities.rb:12:in `chdir'
	from /stackskills-dl-master/lib/utilities.rb:12:in `mkchdir'
	from /stackskills-dl-master/lib/course.rb:22:in `download'
	from /stackskills-dl-master/lib/course_finder.rb:13:in `block (2 levels) in run'
	from /stackskills-dl-master/lib/course_finder.rb:41:in `block in execute'
	from /stackskills-dl-master/lib/course_finder.rb:36:in `each'
	from /stackskills-dl-master/lib/course_finder.rb:36:in `execute'
	from /stackskills-dl-master/lib/course_finder.rb:12:in `block in run'
	from /stackskills-dl-master/lib/utilities.rb:13:in `block in mkchdir'
	from /stackskills-dl-master/lib/utilities.rb:12:in `chdir'
	from /stackskills-dl-master/lib/utilities.rb:12:in `mkchdir'
	from /stackskills-dl-master/lib/course_finder.rb:11:in `run'
	from stackskills_dl.rb:11:in `<main>'

**Comment by yoonwaiyan** [comment]
Hi, thanks for reporting. May I know what's the title for this lecture, and is this course free to access so that I can debug on my side?

**Comment by itsbkm** [comment]
It is not free to access

title is
Class #4: VC Part 2: Security/Legal Structures to Protect You + Make You
More $ (Due diligence and how to assess a management team. Security
structures. Legal information to help protect you and your
investments/company. Venture capital history is very important to
understand.Due diligence and how to assess a management team. Security
structures. Legal information to help protect you and your
investments/company. Venture capital history is very important to
understand).

**Comment by dcous** [comment]
Truncating the course section name corrects this. In course_sections.rb change line 13 to: 
 `    "%02d" % index + ". #{name.slice(0,250)}"`
It's only Class #4 in that course that has the excessive section name, Class #1 just slips under the 256 character maximum.

**Comment by itsbkm** [comment]
Thanks this solved the issue
