### ISSUE TITLE
Download single/list of courses with docker

### ISSUE THREAD

**Issue by Dinesh6777** [yoonwaiyan/stackskills-dl#47]
Hey,
Thank you for the script
By default docker method downloads all courses. Can you include arguments to specify list of course urls

**Comment by yoonwaiyan** [comment]
Please check out https://github.com/yoonwaiyan/stackskills-dl/wiki/Available-Commands for the examples to download single course using course ID or slug and edit the command within docker-compose.yml if you're executing the script using docker-compose.
