### ISSUE TITLE
Unable To Download Any Videos

### ISSUE THREAD

**Issue by theman1616** [yoonwaiyan/stackskills-dl#5]
I am unable to download any videos when running, ruby stackskills_dl.rb on windows, here is the error:

C:\Users\MyUser\Downloads\Stackskills Downloader>ruby stackskills_dl.rb
Login Email: example@example.com
Login password:  mypassword
C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A (OpenSSL::SSL::SSLError)
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
        from C:/Ruby22-x64/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `connect'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:858:in `start'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:700:in `start'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:631:in `connection_for'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:994:in `request'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mechanize-2.7.4/lib/mechanize/http/agent.rb:267:in `fetch'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mechanize-2.7.4/lib/mechanize.rb:464:in `get'
        from stackskills_dl.rb:68:in `<main>'

**Comment by yoonwaiyan** [comment]
Have you try this temporary solution provided in https://github.com/sparklemotion/mechanize/issues/424 ?

**Comment by theman1616** [comment]
No, I might try that.

**Comment by yoonwaiyan** [comment]
Since there's no response, I'll close this issue for now, stated README that Windows is not supported for now.

**Comment by yoonwaiyan** [comment]
Note: an attempt to solve this error on Windows: b33708c8f2db6fd28cc4ed0fc6aa7940c527e1ec
