### ISSUE TITLE
.bin files?

### ISSUE THREAD

**Issue by teamcrisis** [yoonwaiyan/stackskills-dl#52]
Many of the courses are resulting in the download of `.bin` files rather than the video file. Any idea why? It does not happen to all courses, but it seems it might be courses that use `Vimeo`.

**Comment by yoonwaiyan** [comment]
Sorry for the late reply, but I have no idea how the .bin files are generated and I'm currently having issue with the login so I couldn't debug further to verify the issue. If you could solve it please feel free to open PR.
