### ISSUE TITLE
Can't download any file - Sorry, this lecture is not available to download.

### ISSUE THREAD

**Issue by danifunker** [yoonwaiyan/stackskills-dl#6]
I recently install this application on Ubuntu 16.04.01 and am getting the error message
"Sorry, this lecture is not available to download."

When attempting to download a course. This happens for every file in the course. Is there any way to get more verbose information? I think maybe they changed the website and the way you scrape might not be compatible, but I could be totally wrong.

Thanks a lot

**Comment by the-braveknight** [comment]
I cannot download as well...
My idea is to change the script such that it searches in the source code for "https://fast.wistia.net/embed/iframe/*", and then use another script such as 'youtube-dl' to download the link.

**Comment by yoonwaiyan** [comment]
@the-braveknight Thanks, it's a good idea. I couldn't find any full url for wistia videos but I saw wistia video id. Appended the wistia video id to `https://fast.wistia.net/embed/iframe/<wistia_video_id>` works fine using youtube-dl manually though, let me try out with the scraping library.

**Comment by yoonwaiyan** [comment]
apparently it worked! Hope this solves the issues.
