### ISSUE TITLE
Error in downloading videos

### ISSUE THREAD

**Issue by MrTrizaeron** [yoonwaiyan/stackskills-dl#8]
```
Downloading Course_Objective
/home/username/Videos/stackskills-dl/lib/lecture.rb:44:in ``': No such file or directory - youtube-dl (Errno::ENOENT)
   from /home/username/Videos/stackskills-dl/lib/lecture.rb:44:in `download_video'
   from /home/username/Videos/stackskills-dl/lib/lecture.rb:29:in `block in download'
   from /home/username/Videos/stackskills-dl/lib/utilities.rb:11:in `block in mkchdir'
   from /home/username/Videos/stackskills-dl/lib/utilities.rb:10:in `chdir'
   from /home/username/Videos/stackskills-dl/lib/utilities.rb:10:in `mkchdir'
   from /home/username/Videos/stackskills-dl/lib/lecture.rb:28:in `download'
   from /home/username/Videos/stackskills-dl/lib/course.rb:18:in `block (2 levels) in download'
   from /home/username/Videos/stackskills-dl/lib/course.rb:17:in `each'
   from /home/username/Videos/stackskills-dl/lib/course.rb:17:in `block in download'
   from /home/username/Videos/stackskills-dl/lib/utilities.rb:11:in `block in mkchdir'
   from /home/username/Videos/stackskills-dl/lib/utilities.rb:10:in `chdir'
   from /home/username/Videos/stackskills-dl/lib/utilities.rb:10:in `mkchdir'
   from /home/username/Videos/stackskills-dl/lib/course.rb:16:in `download'
   from /home/username/Videos/stackskills-dl/lib/course_finder.rb:10:in `block in run'
   from /home/username/Videos/stackskills-dl/lib/course_finder.rb:37:in `block in execute'
   from /home/username/Videos/stackskills-dl/lib/course_finder.rb:32:in `each'
   from /home/username/Videos/stackskills-dl/lib/course_finder.rb:32:in `execute'
   from /home/username/Videos/stackskills-dl/lib/course_finder.rb:9:in `run'
   from stackskills_dl.rb:8:in `<main>'

```

What could be the reason? I run it in sudo. Ruby version 2.3.1

Thanks!

**Comment by yoonwaiyan** [comment]
Have you installed youtube-dl in your machine?

**Comment by MrTrizaeron** [comment]
My bad for missing ``youtube-dl is required to download Wistia videos.``. Thanks for this script Yoon!

**Comment by vschafflik** [comment]
Yoon, you might want to add this line either to your program or to the description of your application:
sudo apt-get update && sudo apt-get install ruby ruby-bundler wget youtube-dl build-essential gcc zlib1g-dev -y
This helped me to get the script running on my machine.

**Comment by yoonwaiyan** [comment]
@KeksXtreme Thanks for the tips. Did you get the command from somewhere else? Installing Ruby in this way might be ok for non-Ruby developers but normally Ruby is installed via version management systems i.e rvm or rbenv.

**Comment by vschafflik** [comment]
@yoonwaiyan 
No, I didn't get the command from somewhere else. I had to fiddle around a while until I got your script working. Unfortunately I'm not a Ruby Developer and I didn't know about that - thanks for the info! - but Ruby (and the other things mentioned in the script) were not installed on my fresh install of Ubuntu Mate 16.04.1 (as the script wouldn't want to work on Windows - SSL Error - I switched to Linux).

**Comment by MrTrizaeron** [comment]
Thanks for the tip KeksXtreme. 

I am also not a ruby developer and just followed the error messages in the terminal until I have it worked - the last one was this issue which I ultimately missed installing "youtube-dl." 

If only I knew/saw that command beforehand, my installation would have been faster I believe :)

**Comment by yoonwaiyan** [comment]
Added some notes about installing Ruby, closing the issue.
